myapp/urls.py
from django.urls import path
from . import views
from mysite import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='myapp'
urlpatterns = [
    path('',views.IndexView.as_view(),name='main'),
    path('create/',views.MovieCreate.as_view(),name='create'),
    path('update/<int:pk>/',views.MovieUpdate.as_view(),name='update'),
    path('delete/<int:pk>/',views.MovieDelete.as_view(),name='delete'),
    path('details/<int:pk>/',views.MovieDetails.as_view(),name='details')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url('myapp/', include('myapp.urls'))
]

myapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=256)
    poster = models.CharField(max_length=1000)
    director = models.CharField(max_length=256)
    year = models.IntegerField(blank=True, null=True)

    def __str__ (self):
        return self.title
    def get_absolute_url(self):
        return reverse('main')

myapp/views.py
from django.http import HttpResponse
from myapp.models import Movie
from django.urls import reverse_lazy
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    context_object_name = "my_list"
    template_name = "myapp/index.html"
    queryset = Movie.objects.all()

class MovieCreate(generic.CreateView):
    model = Movie
    fields = ['title','poster','director','year']
    template_name_suffix = '_form'
    success_url = reverse_lazy('myapp:main')

class MovieUpdate(generic.UpdateView):
    model = Movie
    fields = ['title','poster','director','year']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('myapp:main')

class MovieDelete(generic.DeleteView):
    model = Movie
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('myapp:main')

class MovieDetails(generic.DetailView):
    template_name_suffix = '_poster'
    queryset = Movie.objects.all()
    def get_object(self):
        obj = super().get_object()
        # Record the last accessed date
        obj.last_accessed = timezone.now()
        obj.save()
        return obj

myapp/templates/myapp/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
<h1>MY AWESOME MOVIES</h1>
<table>
    {% if my_list %}
        <tr>
            <th>Title</th>
            <th>Director</th>
            <th>Year</th>
        </tr>
        {% for movie in my_list %}
            <tr>
                <td>{{movie.title}}</td>
                <td>{{movie.director}}</td>
                <td>{{movie.year}}</td>
                <td><a href="{% url 'myapp:update' movie.id %}">update</a></td>
                <td><a href="{% url 'myapp:delete' movie.id %}">delete</a></td>
                <td><a href="{% url 'myapp:details' movie.id %}">details</a></td>
            </tr>
        {% endfor %}
    {% else %}
         <th>INSERT YOUR DAMN MOVIES</th>
    {% endif %}
</table>
<th><a href="{% url 'myapp:create' %}">Create awesome movie</a></th>

myapp/templates/myapp/movie_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
<th><a href="{% url 'myapp:main' %}">Back</a></th>

myapp/templates/myapp/movie_form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
<h1>INSERT AWESOME MOVIE</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
<th><a href="{% url 'myapp:main' %}">Back</a></th>

myapp/templates/myapp/movie_poster.html
<img src="{{ obj.poster.url }}">
<th><a href="{% url 'myapp:main' %}">Back</a></th>

myapp/templates/myapp/movie_update_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
<th><a href="{% url 'myapp:main' %}">Back</a></th>